# EXPERIMENT 2 - NUMERICAL PYTHON

In [1]:
# Library Initialization
import numpy as np

In [2]:
# Problem 1 - NORMALIZATION PROBLEM

# Initial Variable Declaration
X = np.random.random((5,5)) # Using the variable given in the experiment sheet.

# Normalization
def normalize(x): # I decided on creating a function because modularity is a general coding principle.
    z = (x - x.mean()) / x.std() # Translating, this is simply the formula Z = X - xbar / omega.
    np.save('X_normalized.npy', z) # Saving to the file name as required by the problem.
    print(np.load('X_normalized.npy')) # Print to simply see the saved file using np.load.

normalize(X) # Test Case

[[ 0.89750398  0.63659478  1.09434924 -1.354749    0.48913874]
 [ 1.06979788 -1.35871421 -1.2783632  -0.02061181  0.85482897]
 [ 0.3255369  -1.37274713  1.26267475  0.40316395 -0.94934644]
 [-1.18221465 -0.50570532  1.14201569  1.10875425 -1.27642315]
 [ 0.42349978 -1.2022499   1.11279892  0.78422596 -1.10375899]]


In [3]:
# Problem 2 - DIVISIBLE BY 3 PROBLEM

# Initial Variable Declaration
A = np.arange(1,101) ** 2 # First I create the array of squares from 1-1001 because its non inclusive.
A = A.reshape(10,10) # Then, using the reshape function of np.arrays, I reshape the function to 10x10.

# Finding values divisible by 3
B = A[A % 3 == 0] # Using indexing, we can search for all values of A that are divisible by 3 and have no remainder using modulo division.
np.save('div_by_3.npy', B) # Saving to the file name as required by the problem.

print(B) # Test Case 1, Printing B for review.

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
